import type { Part, Platform, PlatformId } from "./types";

export const PLATFORMS: Platform[] = [
  {
    id: "aap-01",
    name: "AAP-01",
    description: "Gas blowback pistol platform",
  },
  {
    id: "hi-capa",
    name: "Hi-Capa",
    description: "1911-style competition pistol",
  },
];

export const PARTS_CATALOG: Part[] = [
  {
    id: "aap-frame-01",
    name: "CNC Aluminum Frame",
    category: "frame",
    stl_url: "/models/placeholder-pistol.stl",
    estimated_price: 189.99,
    durability_note: "CNC aluminum — high cycle life, resists frame cracking",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-slide-01",
    name: "TDC Slide Kit",
    category: "slide",
    stl_url: "/models/aap-01/slide-01.stl",
    estimated_price: 124.99,
    durability_note: "Steel breech face — tolerates high-ROF gas setups",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-barrel-01",
    name: "CNC 6.03 Inner Barrel",
    category: "barrel",
    stl_url: "/models/aap-01/barrel-01.stl",
    estimated_price: 34.99,
    durability_note: "Stainless steel — minimal wear over 10K+ rounds",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-hop-01",
    name: "Autobot Hop-Up",
    category: "hop-up",
    stl_url: "/models/aap-01/hop-up-01.stl",
    estimated_price: 29.99,
    durability_note: "Bucking wears every 5–8K rounds — budget for replacements",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-mag-01",
    name: "Extended Magazine",
    category: "magazine",
    stl_url: "/models/aap-01/magazine-01.stl",
    estimated_price: 44.99,
    durability_note: "Feed lips may fatigue — inspect after heavy use",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-grip-01",
    name: "Tactical Grip Panel",
    category: "grip",
    stl_url: "/models/aap-01/grip-01.stl",
    estimated_price: 18.99,
    durability_note: "Polymer — cosmetic wear only, no functional impact",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-trigger-01",
    name: "Flat Trigger Shoe",
    category: "trigger",
    stl_url: "/models/aap-01/trigger-01.stl",
    estimated_price: 24.99,
    durability_note: "Aluminum shoe — long-lasting, no sear wear",
    compatibility: ["aap-01"],
  },
  {
    id: "aap-sights-01",
    name: "RMR Cut Slide Sights",
    category: "sights",
    stl_url: "/models/aap-01/sights-01.stl",
    estimated_price: 59.99,
    durability_note: "Steel construction — fiber inserts replaceable",
    compatibility: ["aap-01"],
  },
  {
    id: "hc-frame-01",
    name: "Stainless Steel Frame",
    category: "frame",
    stl_url: "/models/hi-capa/frame-01.stl",
    estimated_price: 349.99,
    durability_note: "Full steel — handles CO2 and high-pressure builds",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-slide-01",
    name: "Gold Match Slide",
    category: "slide",
    stl_url: "/models/hi-capa/slide-01.stl",
    estimated_price: 279.99,
    durability_note: "Lightened slide — monitor blowback timing under stress",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-barrel-01",
    name: "Crazy Jet 6.03 Barrel",
    category: "barrel",
    stl_url: "/models/hi-capa/barrel-01.stl",
    estimated_price: 39.99,
    durability_note: "Stainless inner — excellent longevity with proper cleaning",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-hop-01",
    name: "Maxx Model Hop-Up",
    category: "hop-up",
    stl_url: "/models/hi-capa/hop-up-01.stl",
    estimated_price: 54.99,
    durability_note: "Adjustable arm — re-tune after 3K round break-in",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-mag-01",
    name: "Extended Hi-Capa Mag",
    category: "magazine",
    stl_url: "/models/hi-capa/magazine-01.stl",
    estimated_price: 38.99,
    durability_note: "Metal base — gas route seals degrade over time",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-grip-01",
    name: "Stippled Grip Tape",
    category: "grip",
    stl_url: "/models/hi-capa/grip-01.stl",
    estimated_price: 14.99,
    durability_note: "Adhesive tape — replace when texture wears smooth",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-trigger-01",
    name: "Adjustable Trigger",
    category: "trigger",
    stl_url: "/models/hi-capa/trigger-01.stl",
    estimated_price: 89.99,
    durability_note: "Match-grade — check set screw lock after 2K rounds",
    compatibility: ["hi-capa"],
  },
  {
    id: "hc-sights-01",
    name: "Fiber Optic Front / Rear",
    category: "sights",
    stl_url: "/models/hi-capa/sights-01.stl",
    estimated_price: 74.99,
    durability_note: "Fiber rods fade in UV — cheap to swap",
    compatibility: ["hi-capa"],
  },
];

export const CATEGORY_LABELS: Record<Part["category"], string> = {
  frame: "Frame",
  slide: "Slide",
  barrel: "Barrel",
  "hop-up": "Hop-Up",
  magazine: "Magazine",
  grip: "Grip",
  trigger: "Trigger",
  sights: "Sights",
};

export function getPartsForPlatform(platformId: PlatformId): Part[] {
  return PARTS_CATALOG.filter((p) => p.compatibility.includes(platformId));
}
